kind: Deployment
apiVersion: apps/v1
metadata:
  name: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
      - name: data-api-pod
        image: gcr.io/servicesproject-246513/final-data-api
        ports:
        - containerPort: 80
        env:
        - name: MONGO_CONNSTR
          value: mongodb://mongodb-svc.default
      imagePullSecrets:
      - name: acr-auth